const data = [
    {
        id: "1",
        image:"https://images.pexels.com/photos/834892/pexels-photo-834892.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        title: "QUANTITY SURVEYOR",
        paragraph1: "Quantity surveyors estimate and control costs for large construction projects. They make sure that structures meet legal and quality standards. Quantity surveyors are involved at every stage of a project. Whether they’re working on residential, commercial or industrial projects, clients rely on them to ensure that the final outcome is value for money.",
        become: "How to become a quantity surveyor",
        becomepara: "There are several routes to becoming a quantity surveyor. You can gain the qualifications you need by doing a university course or an apprenticeship. If you already have relevant experience you may be able to apply directly to an employer or train on the job. You should explore the options to find out which is the right one for you.  You may need a Construction Skills Certification Scheme (CSCS) card to work on a construction site. If you already hold an unrelated first degree you could complete a postgraduate conversion course. This should be accredited by the Royal Institution of Chartered Surveyors (RICS) and the Chartered Institute of Building (CIOB).You could gain a postgraduate surveying qualification via a graduate trainee scheme with a construction or surveying company. The University College of Estate Management offers postgraduate distance learning courses. ",
        work: "If you have relevant experience in a related area of work, such as accountancy, you may be able to study part-time to become a quantity surveyor. Work experience is essential to gaining employment within the construction industry. You could gain this at school, or by working weekends and holidays with a company or relative who works as a quantity surveyor. Potential employers will always be pleased to see work experience listed on your CV. ",
        skill: "Additional skills which may benefit anyone looking to become a quantity surveyor include:     Strong maths knowledge   ,   Excellent attention to detail ,Analytical thinking skills,  Understanding of engineering science and technology,  Knowledge of building and construction, Ability to use your initiative.",
    },
    {
        id: "2",
        title: "LAND SURVEYOR",
        image:"https://images.pexels.com/photos/110469/pexels-photo-110469.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        paragraph1: "Land surveyors measure and map the shape of land. They gather data for civil engineering and construction projects so that accurate site plans can be drawn. As a surveyor, you’ll be part of a fast-moving, technologically advanced industry. Much of your time will be spent on-site, using technical instruments to record the environment.",
        become: "How to become a land surveyor",
        becomepara: "You can gain the qualifications you need by doing a university course, a graduate training scheme, or an apprenticeship. You may need a Construction Skills Certification Scheme (CSCS) card to work on a construction site. UniversityYou will need to complete a degree accredited by the Royal Institution of Chartered Surveyors (RICS). Relevant subjects include surveying, civil engineering, geomatics or geographical information science.For an undergraduate degree, you’ll need: 5 GCSEs (including English and maths) at grade 4 (C) or above, or equivalent2 - 3 A levels, or equivalent.f your first degree isn’t relevant to surveying, you could do a postgraduate conversion course at university, or through an employer.You could also gain higher qualifications through an employer’s graduate training scheme. If you have a foundation degree or graduate diploma in surveying, you could get a graduate job as a surveying technician. You could then apply for RICS membership and study to be a fully qualified land surveyor. Some people become surveyors by working for a surveying practice and completing a distance learning course with the University College of Estate Management",
        work: "Work experience  Work experience is essential to gaining employment within the construction industry. You could gain this at school, or by working weekends and holidays with a company or relative who works in construction. Potential employers will always be pleased to see work experience listed on your CV.",
        skill: "Additional skills which may benefit anyone considering a job as a land surveyor include:   Knowledge of engineering science, maths, geography, and technology,  Analytical thinking skills, Be thorough and pay attention to detail,  Able to use your initiative, Excellent verbal communication skills,Thinking and reasoning skills,Able to use a computer and the main software packages competently"

    },
    {
        id: "3",
        title: "Primavera (software)",
        image:"https://images.pexels.com/photos/3862379/pexels-photo-3862379.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        paragraph1: "There are a lot of project management software tools to choose from, and there are a few that truly seem to dominate the space, like Oracle’s Primavera P6. How can you find the project management solution that fits your organization, project and the way your team works? The first thing to do is understand what these tools are and the feature set they offer.  Primavera P6 is the product of the multinational computer technology corporation Oracle. For such a well-known brand, it’s a product that doesn’t have great name recognition, even among those in the industry. It’s time to change that. Let’s take a closer look at Primavera P6 to see what it can do and if it’s right the right choice for your project management needs.",
        become: "Pros and Cons of Primavera P6",
        becomepara: "There are some things that Primavera P6 does well, along with some features that have some drawbacks. If you’re still on the fence, here’s a look at its pros and cons.",
        work: "The P6 Professional Project Management (PPM) from Primavera will cost $2,570 for an annual subscription. That price includes $2,020 plus an annual maintenance fee of $550 for upgrades, fixes, patches, etc. The renewal of the maintenance cost is not required, but it’s suggested.There’s also the enterprise option, Primavera P6 Enterprise Professional Project Management (EPPM). This version of Primavera P6 is accessed via the web, rather than being a desktop software application like the P6 PPM option. This option will run you $2,750 for a perpetual license, which includes an annual maintenance fee of $605.Last, there’s the Oracle Primavera Cloud, which is a much cheaper and much less-feature rich offering at $125 a month. It also has the added benefits of faster delivery and fosters collaboration to improve efficiency and quality. The cloud-based tool will also connect teams over any device and update activities and tasks instantly.",
        skill: "It’s flexible when it comes to organizing lots of activities, with one platform that allows users to prioritize, execute and monitor their work, A multiuser system lets teams work at the same time on the same project across the organization.,  Real-time reporting provides meaningful data delivered fast, either on-demand or scheduled.,  The dashboard allows users to manage a single project or even a portfolio, with great flexibility.,Primavera P6 integrates with Oracle and other third-party products.,  P6 can be used on multiple devices, such as tablets and mobile devices for access anywhere and at any time.,  P6 works on Windows as a desktop (or web app with the Enterprise option)."

    },
    {
        id: "4",
        title: "AutoCAD For Civil Engineers ",
        image:"https://images.pexels.com/photos/5380642/pexels-photo-5380642.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        paragraph1: "AutoCAD is a program extensively used by civil engineers and other professionals all over the world. It allows a designer to analyse, design and plan easily and efficiently. If you are a professional in this field or aspire to become a civil engineer, it might be beneficial for you to have a good understanding about AutoCAD and its features. In this article, we discuss what AutoCAD is, how AutoCAD is useful for civil engineers and some other software programs a civil engineer may use.Even though there are numerous engineering design tools available in the market, AutoCAD for civil engineers is most popular because of its simplicity and user-friendliness. Typically, all civil engineering students train to use AutoCAD software. In a civil engineering course, your university syllabus may contain a module on AutoCAD and its uses. If a student aspires to be successful in the civil engineering, design or detailing field, then AutoCAD may be an essential tool to learn. AutoCAD is flexible enough to be used in almost all fields relating to civil engineering. Apart from making 3D models, it can also be used to create documents, drafts and 2D drawings.AutoCAD is a computer-aided design (CAD) and drafting software application created by the company Autodesk. A range of professionals like architects, city planners and graphic designers use it. AutoCAD has become one of the most widely used CAD programs worldwide. The software allows you to draw and edit 2D and 3D designs more efficiently. Corrections and edits can be time-consuming while working by hand on a physical medium. You can access easily AutoCAD designs from anywhere as the software also provides cloud integration.AutoCAD is available in many global languages like English, Chinese, German, French, Italian, Japanese, Korean, Spanish, Polish, Hungarian and Russian. It supports a variety of extensions and numerous plugins, available in the application store. The company has also developed programs which are discipline specific like AutoCAD Architecture, AutoCAD Electrical, AutoCAD Mechanical and Advance Steel.",
        become: "What are the benefits of using AutoCAD in civil engineering?",
        becomepara: "It is user-friendly,   It is easily available,   You can get certified by Autodesk ,It offers a high level of accuracy, It makes editing easy,It reduces the chance for errors, It allows you to store and transfer data,It saves time and money,It enables collaboration,",
        work: "Features of AutoCAD",
        skill: "3D modelling and visualisation,Photorealistic rendering,Solid, surface and mesh modelling,Base, projected and section views,Visual styles,Smart dimensioning,PDF and DGN import, export and underlay,Section planes,Parametric constraints,3D scanning and point cloud generation,2D drafting, drawing and annotation,3D navigation"

    }
]


export default data;